задачи 1, 3, 4, 5
js-tasks-ru/jsbasic-20210621_kelbikhanov2202 pull request #2
Opened 2021-06-30 15:52 UTC by Kelbikhanov

2021-06-30 15:52 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-30 16:01 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-01 09:49 UTC, SinimaWath requested changes
А зачем ты удалил из у себя 1-module/4-tasks?

2021-07-01 09:49 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  var res = 1 ;
Давай не использовать var, мы до этого рассмотрели все его проблемы

2021-07-01 09:49 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  for( i = 0; i < n; i++) {
нужно обьявлять переменную i через let

2021-07-01 15:37 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-01 15:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-02 13:50 UTC, SinimaWath requested changes

2021-07-02 13:50 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return upperStr.includes('1Xbet') || upperStr.includes('XXX');
Надо еще 1Xbet в upperCase

2021-07-02 13:50 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return upperStr.includes('1Xbet') || upperStr.includes('XXX');
Давай это поправим, все остальное ок

2021-07-03 17:11 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-04 12:46 UTC, SinimaWath requested changes

2021-07-04 12:46 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return lowerStr.includes('1xBet'[1, 4].toUpperCase() ) || lowerStr.toUpperCase().includes('XXX');
Не понимаю зачем тут  `'1xBet'[1, 4].toUpperCase()`? Эта операция возвращает `T`, и остальные буквы не возвращаются.

Напиши `'1xBet'.toUpperCase()` - toUpperCase() - это метод строки, который всю строку может перевести

2021-07-04 16:01 UTC, Kelbikhanov commented on 1-module/4-task/index.js
> +  return lowerStr.includes('1xBet'[1, 4].toUpperCase() ) || lowerStr.toUpperCase().includes('XXX');
я пробовал так сделать, выдает ошибку

2021-07-04 16:05 UTC, Kelbikhanov commented on 1-module/4-task/index.js
> +  return lowerStr.includes('1xBet'[1, 4].toUpperCase() ) || lowerStr.toUpperCase().includes('XXX');
залил последние изменения, иначе почему то не работает

2021-07-04 16:05 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-05 21:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-06 16:35 UTC, SinimaWath approved these changes
Все круто!

2021-07-06 16:36 UTC, merged